# Use the last version ubuntu
FROM ubuntu:latest

# Updates the list of packages and upgrades installed software
RUN apt-get update && apt-get upgrade -y

# Command that runs when the container starts
CMD echo "Hello, World!"